name 'poise-cloudformation'
maintainer 'Luis De Siqueira'
maintainer_email 'Louthebrew@gmail.com'
license 'MIT'
description 'Installs/Configures cloudformation'
long_description 'Installs/Configures cloudformation'
version '0.0.1'

depends 'poise'
depends 'python'
